version: "3"

services:
  allredlib_db:
    image: "postgres:12"
    container_name: "allredlib_db"
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${ALLREDLIB_PGUSER}
      POSTGRES_PASSWORD: ${ALLREDLIB_PGPASS}
      POSTGRES_DB: ${ALLREDLIB_DB}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - allredlib_dbdata:/var/lib/postgresql/data_allredlib

volumes:
  allredlib_dbdata:

