{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeFamilies #-}

module Handler.Book where

import Import

type Title' = String

type Author = String

data Book =
  Book Title' Author
  deriving (Show)

instance ToJSON Book where
  toJSON (Book title author) = object ["title" .= title, "author" .= author]

dummyBooks :: [Book]
dummyBooks =
  [ Book "Title" "Author"
  , Book
      "A Shorter Summa: The Most Essential Philosophical Passages of St. Thomas Aquinas' Summa Theologica"
      "(Aquinas), Saint Thomas; Kreeft, Peter"
  , Book
      "Literature: The Human Experience Shorter Edition: Reading and Writing"
      "Abcarian, Richard; Klotz, Marvin"
  , Book "Chinese Phrases For Dummies" "Abraham, Wendy"
  , Book "Things Fall Apart" "Achebe, Chinua"
  , Book "The hitchhiker's guide to the galaxy" "Adams, Douglas"
  , Book "Tales from Watership Down" "Adams, Richard"
  , Book "Watership Down: A Novel" "Adams, Richard"
  , Book
      "The Question and Answer Book: Our Amazing Sun"
      "Adams, Richard Crittenden"
  , Book "Purple Hibiscus: A Novel" "Adichie, Chimamanda Ngozi"
  , Book "Lady of Devices: A Steampunk Adventure Novel" "Adina, Shelley"
  , Book "The Question and Answer Book: World of Weather" "Adler, David"
  , Book
      "How to Read a Book"
      "Adler, Mortimer Jerome; Doren, Charles Lincoln Van"
  , Book "Chinese Whiskers: A Novel" "Aiyar, Pallavi"
  , Book
      "Linguistics: An Introduction to Language and Communication"
      "Akmajian, Adrian; Demers, Richard A.; Farmer, Ann K."
  , Book "Taran Wanderer" "Alexander, Lloyd"
  , Book "The Black Cauldron" "Alexander, Lloyd"
  , Book "The Book of Three" "Alexander, Lloyd"
  , Book "The Castle of Llyr" "Alexander, Lloyd"
  , Book "The High King" "Alexander, Lloyd"
  , Book "The Iron Ring" "Alexander, Lloyd"
  , Book "The Inferno" "Alighieri, Dante"
  , Book "The Portable Dante" "Alighieri, Dante"
  , Book
      "The Divine Comedy of Dante Alighieri: Paradiso"
      "Alighieri, Dante; Mandelbaum, Allen"
  , Book "Boy Scout Handbook" "America, Boy Scouts of"
  , Book "First Thousand Words in Chinese" "Amery, Heather"
  , Book
      "Quantitative Methods for Business"
      "Anderson, David Ray; Sweeney, Dennis J.; Williams, Thomas Arthur"
  , Book "Black Cat" "Andrews, V. C."
  , Book "Flowers in the Attic" "Andrews, V. C."
  , Book "The Gates of Winter" "Anthony, Mark"
  , Book "The Keep of Fire" "Anthony, Mark"
  , Book
      "A Spell for Chameleon (The Parallel Edition... Simplified)"
      "Anthony, Piers"
  , Book "Castle Roogna" "Anthony, Piers"
  , Book "Centaur Aisle" "Anthony, Piers"
  , Book "Night mare" "Anthony, Piers"
  , Book "Ogre, Ogre" "Anthony, Piers"
  , Book "Source of Magic" "Anthony, Piers"
  , Book "Up In a Heaval" "Anthony, Piers"
  , Book
      "A House Called Awful End: Book One in the Eddie Dickens Trilogy"
      "Ardagh, Philip"
  , Book "The Complete Plays of Aristophanes" "Aristophanes"
  , Book "My Life and Times! A Journal" "Ashby, Clarin"
  , Book "My Prose and Poetry: Plus the Story Behind the Verse" "Ashby, Clarin"
  , Book "Sage Brush and Rose Buds" "Ashby, Clarin"
  , Book
      "Before I Grew Old: Childhood Memories of Homestead Life in the Uintah Basin"
      "Ashby, Clarin D."
  , Book "Saints and Raging Seas: A Trial of Faith" "Ashby, Clarin D."
  , Book "Stephen, A Prophet's Friend" "Ashby, Clarin D."
  , Book "ID: The Second Machine Dynasty" "Ashby, Madeline"
  , Book "VN: The First Machine Dynasty" "Ashby, Madeline"
  , Book
      "The Guns at Last Light: The War in Western Europe, 1944-1945"
      "Atkinson, Rick"
  , Book "The Handmaid's Tale" "Atwood, Margaret"
  , Book "Pride and Prejudice" "Austen, Jane"
  , Book "Midnight Magic" "Avi"
  , Book "Beautiful Origami" "Aytüre-Scheele, Zülal"
  , Book "Red Cavalry" "Babelʹ, Isaak; Babel, Nathalie; Constantine, Peter"
  , Book "Fairy Wings" "Baker, Elizabeth Dawson"
  , Book
      "Introduction to International Political Economy"
      "Balaam, David N.; Dillman, Bradford L."
  , Book "The Creature from the Seventh Grade" "Balaban, Bob"
  , Book "The Curious Writer" "Ballenger, Bruce"
  , Book "Peter and Wendy" "Barrie, James Matthew"
  , Book "Peter Pan in Kensington Gardens" "Barrie, James Matthew"
  , Book "The Mirror of Merlin" "Barron, T. A."
  , Book "English Grammar: Language as Human Behavior" "Barry, Anita K."
  , Book "The Red Blazer Girls: The Ring of Rocamadour" "Beil, Michael D."
  , Book "The Kindling" "Bell, Braden"
  , Book "The Goblin Wood" "Bell, Hilari"
  , Book "Bard's Oath" "Bertin, Joanne"
  , Book
      "Damned Lies and Statistics: Untangling Numbers from the Media, Politicians, and Activists"
      "Best, Joel"
  , Book "State Government" "Beyle, Thad"
  , Book
      "A History of the Arab-Israeli Conflict"
      "Bickerton, Ian J.; Klausner, Carla L."
  , Book "Doll Bones" "Black, Holly"
  , Book "The Crystal Rose" "Bohnhoff, Maya Kaathryn"
  , Book "Dreams and dreaming" "Books, Time-Life"
  , Book "Narraciones" "Borges, Jorge Luis"
  , Book "A History of Mathematics" "Boyer, Carl B."
  , Book "Fahrenheit 451" "Bradbury, Ray"
  , Book "Something Wicked This Way Comes" "Bradbury, Ray"
  , Book "Down a Lost Road" "Bralick, J. Leigh"
  , Book "Hedgie loves to read" "Brett, Jan"
  , Book "dRaGoN bOnEs" "Briggs, Patricia"
  , Book "Wuthering Heights" "Brontë, Emily"
  , Book "The Mythical Man-Month" "Brooks, Frederick P., Jr."
  , Book "The Elfstones of Shannara" "Brooks, Terry"
  , Book "The Talismans of Shannara" "Brooks, Terry"
  , Book "The Wishsong of Shannara" "Brooks, Terry"
  , Book
      "Utah Politics Under the Dome: Representation and the Utah Legislature"
      "Brown, Adam R."
  , Book "Angels & Demons" "Brown, Dan"
  , Book "The Da Vinci Code" "Brown, Dan"
  , Book "Bury my heart at Wounded Knee" "Brown, Dee Alexander"
  , Book
      "Vignettes of Taiwan: Short Stories, Essays & Random Meditations about Taiwan"
      "Brown, Joshua Samuel"
  , Book "Evanescent" "Buchanan, Andria"
  , Book "Paladin of Souls" "Bujold, Lois McMaster"
  , Book "11:15: The Making of a Halfling (FREE ebook)" "Burch, Heather"
  , Book "The Secret Garden" "Burnett, Frances Hodgson"
  , Book
      "Baroque & Pieces: A Novel Approach to Understanding Classical Music"
      "Burton, Warren Lindsay"
  , Book "Cold Days: A Novel of the Dresden Files" "Butcher, Jim"
  , Book
      "Don Juan"
      "Byron, George Gordon Byron Baron; Steffan, Truman Guy; Steffan, E.; Pratt, Willis Winslow"
  , Book
      "What I Wish I'd Known in High School: A Crash Course in Teenage Survival"
      "Bytheway, John"
  , Book
      "What I Wish I'd Known in High School: The Second Semester"
      "Bytheway, John"
  , Book "How to Read Chinese Poetry: A Guided Anthology" "Cai, Zong-qi"
  , Book "La Venezuela civil: Constructores de la republica" "Caldera, Rafael"
  , Book "Great Explorations: Vasco da Gama" "Calvert, Patricia"
  , Book
      "Chicken Soup for the Sister's Soul: 101 Inspirational Stories about Sisters and Their Changing Relationships"
      "Canfield, Jack; Mitchell, Nancy; McNamara, Heather"
  , Book "The Story of the Stone: The Crab-flower Club" "Cao, Xueqin"
  , Book "The Story of the Stone: The golden days" "Cao, Xueqin"
  , Book
      "The Story of the Stone: The warning voice"
      "Cao, Xueqin; Hawkes, David; Minford, John"
  , Book "Children of the Mind" "Card, Orson Scott"
  , Book "Enchantment" "Card, Orson Scott"
  , Book "Ender In Exile" "Card, Orson Scott"
  , Book "Ender's Game" "Card, Orson Scott"
  , Book "Ender's Shadow" "Card, Orson Scott"
  , Book "Heartfire: The Tales of Alvin Maker" "Card, Orson Scott"
  , Book "Shadow of the Giant" "Card, Orson Scott"
  , Book "Shadow of the Hegemon" "Card, Orson Scott"
  , Book "Shadow Puppets" "Card, Orson Scott"
  , Book "Speaker for the Dead" "Card, Orson Scott"
  , Book "Xenocide: Volume Three of the Ender Quintet" "Card, Orson Scott"
  , Book "The Memory of Earth (Homecoming volume 1)" "Card, Orson Scott"
  , Book "The Call of Earth (Homecoming volume 2)" "Card, Orson Scott"
  , Book "The Ships of Earth (Homecoming volume 3)" "Card, Orson Scott"
  , Book "Beyond the Valley of Thorns" "Carman, Patrick"
  , Book "Into the Mist" "Carman, Patrick"
  , Book "The Exceptionals" "Cashman, Erin Theresa"
  , Book "Fire" "Cashore, Kristin"
  , Book "Graceling" "Cashore, Kristin"
  , Book "Betrayed" "Cast, P C and Kristin Cast"
  , Book "Marked" "Cast, P C and Kristin Cast"
  , Book
      "The Symbols of Christmas: Finding the Meaning in the Symbols of the Season"
      "Castor, Rachelle Pace"
  , Book
      "Late for Tea at the Deer Palace: The Lost Dreams of My Iraqi Family"
      "Chalabi, Tamara"
  , Book "Wild Swans: Three Daughters of China" "Chang, Jung"
  , Book "Mao: The Unknown Story" "Chang, Jung and Jon Halliday"
  , Book
      "Mathematical Proofs: A Transition to Advanced Mathematics"
      "Chartrand, Gary; Polimeni, Albert D.; Zhang, Ping"
  , Book "Canterbury Tales" "Chaucer, Geoffrey"
  , Book "The Plays of Anton Tchekov" "Chekhov, Anton"
  , Book
      "龙文墨影:大学文言读本Language of the Dragon: A Classical Chinese Reader"
      "Chiang, Gregory"
  , Book "Clarice Bean, Don't Look Now" "Child, Lauren"
  , Book
      "The Power of Everyday Missionaries: The What and How of Sharing the Gospel"
      "Christensen, Clayton M."
  , Book "If Our Stones Could Talk" "Christensen, Sharon"
  , Book "And Then There Were None" "Christie, Agatha"
  , Book "The House on Mango Street" "Cisneros, Sandra"
  , Book "City of Bones: The Mortal Instruments" "Clare, Cassandra"
  , Book "The Infernal Devices: Book One" "Clare, Cassandra"
  , Book
      "A History of the Modern Middle East"
      "Cleveland, William L.; Bunton, Martin P."
  , Book "The Forever King" "Cochran, Molly; Murphy, Warren"
  , Book "Global Political Economy" "Cohn, Theodore H."
  , Book "Open City: A Novel" "Cole, Teju"
  , Book
      "The Rime of the Ancient Mariner"
      "Coleridge, Samuel Taylor and Gustave Doré"
  , Book "Artemis Fowl: The Lost Colony" "Colfer, Eoin"
  , Book "Artemis Fowl: The Time Paradox" "Colfer, Eoin"
  , Book "Mockingjay" "Collins, Suzanne"
  , Book "The Hunger Games" "Collins, Suzanne"
  , Book "The Hunger Games: Catching Fire" "Collins, Suzanne"
  , Book "Revolution is Not a Dinner Party" "Compestine, Ying Chang"
  , Book "My Daniel" "Conrad, Pam"
  , Book "The Diamond Deep" "Cooper, Brenda"
  , Book
      "J. R. R. Tolkien: The Man who Created The Lord of the Rings"
      "Coren, Michael"
  , Book
      "The Lord of the Rings: The Fellowship of the Ring: Visual Companion"
      "Coren, Michael"
  , Book "Todos los fuegos el fuego" "Cortázar, Julio"
  , Book "The Power of One" "Courtenay, Bryce"
  , Book "Bismarck" "Crankshaw, Edward"
  , Book "The Crow" "Croggon, Alison"
  , Book "The Naming" "Croggon, Alison"
  , Book "The Riddle" "Croggon, Alison"
  , Book "The Singing" "Croggon, Alison"
  , Book
      "Talented Teenagers: The Roots of Success and Failure"
      "Csikszentmihalyi, Mihaly; Rathunde, Kevin; Whalen, Samuel"
  , Book "Sahara" "Cussler, Clive"
  , Book "Cyr's Third Reader" "Cyr, Ellen M."
  , Book "Fire Star" "d'Lacey, Chris"
  , Book "Icefire" "d'Lacey, Chris"
  , Book "The Fire Within" "d'Lacey, Chris"
  , Book "Random House German-English English-German Dictionary" "Dahl, Anne"
  , Book "Charlie and the Chocolate Factory" "Dahl, Roald"
  , Book "George’s Marvelous Medicine" "Dahl, Roald"
  , Book "The Big Friendly Giant" "Dahl, Roald"
  , Book "The Twits" "Dahl, Roald"
  , Book "The Witches" "Dahl, Roald"
  , Book "Balzac and the Little Chinese Seamstress" "Dai, Sijie; Rilke, Ina"
  , Book "Amber Brown Goes Fourth" "Danziger, Paula"
  , Book "The Aztecs, a History" "Davies, Nigel"
  , Book
      "Don't Know Much About History: Everything You Need to Know About American History But Never Learned"
      "Davis, Kenneth C."
  , Book "The Chinese Have a Word for It" "De Mente, Boyé Lafayette"
  , Book "Tam Lin" "Dean, Pamela"
  , Book "The Secret Country" "Dean, Pamela"
  , Book "Death by Chocolate" "Desaulniers, Marcel"
  , Book "Total Quality Control in the Clinical Laboratory" "Dharan, Murali"
  , Book "The Tale of Despereaux" "DiCamillo, Kate"
  , Book "The Tiger Rising" "DiCamillo, Kate"
  , Book "A Tale of Two Cities" "Dickens, Charles"
  , Book "Out of Africa; Shadows on the Grass" "Dinesen, Isak"
  , Book "A Discipline of Programming" "Djikstra, Edsger Wybe"
  , Book "The Idiot" "Dostoyevsky, Fyodor"
  , Book "Enchanter: Book Two of The Wayfarer Redemption" "Douglass, Sara"
  , Book "Pilgrim: Book Five of the Wayfarer Redemption" "Douglass, Sara"
  , Book "Sinner" "Douglass, Sara"
  , Book "Starman" "Douglass, Sara"
  , Book "The Wayfarer Redemption: Book One" "Douglass, Sara"
  , Book
      "The Bible: A Story of God and All of Us"
      "Downey, Roma and Mark Burnett"
  , Book "The Complete Sherlock Holmes" "Doyle, Arthur Conan"
  , Book
      "Manual de Gramatica: Grammar Reference for Students of Spanish"
      "Dozier, Eleanor; Iguina, Zulma"
  , Book "Bartholomew and the Oobleck" "Dr. Seuss"
  , Book "Dr. Seuss's ABC" "Dr. Seuss"
  , Book "Green Eggs and Ham" "Dr. Seuss"
  , Book "Hooper Humperdink...? Not Him!" "Dr. Seuss"
  , Book "If I Ran The Circus" "Dr. Seuss"
  , Book "There's a Wocket in My Pocket" "Dr. Seuss"
  , Book "Wacky Wednesday" "Dr. Seuss"
  , Book "Lord of the Isles" "Drake, David"
  , Book "The Unicorn's Secret: The silver thread" "Duey, Kathleen"
  , Book "Silver Thread" "Duey, Kathleen; Rayyan, Omar"
  , Book "The count of Monte-Cristo" "Dumas, Alexandre"
  , Book "The Other Lands" "Durham, David Anthony"
  , Book "Castle of Wizardry" "Eddings, David"
  , Book "Demon Lord of Karanda" "Eddings, David"
  , Book "Enchanters' End Game" "Eddings, David"
  , Book "Guardians of the West" "Eddings, David"
  , Book "King of the Murgos" "Eddings, David"
  , Book "Magician's Gambit" "Eddings, David"
  , Book "Pawn of Prophecy" "Eddings, David"
  , Book "Queen of Sorcery" "Eddings, David"
  , Book "Sorceress of Darshiva" "Eddings, David"
  , Book "The Hidden City" "Eddings, David"
  , Book "The Sapphire Rose" "Eddings, David"
  , Book "The Elder Gods (The Dreamers book 1)" "Eddings, David; Eddings, Leigh"
  , Book "Belgarath the Sorcerer" "Eddings, David; Eddings, Leigh"
  , Book "Polgara the Sorceress" "Eddings, David; Eddings, Leigh"
  , Book "Domes of Fire (The Tamuli book 1)" "Eddings, David"
  , Book "The Shining Ones (The Tamuli book 2)" "Eddings, David"
  , Book "The Diamond Throne (The Elenium book 1)" "Eddings, David"
  , Book "The Seeress of Kell (The Malloreon book 5)" "Eddings, David"
  , Book
      "Secrets of the Millionaire Mind: Mastering the Inner Game of Wealth"
      "Eker, T. Harv"
  , Book "The History of Our Country: Volume 1" "Ellis, Eward S."
  , Book "The History of Our Country: Volume 2" "Ellis, Eward S."
  , Book "The History of Our Country: Volume 3" "Ellis, Eward S."
  , Book "The History of Our Country: Volume 4" "Ellis, Eward S."
  , Book "The History of Our Country: Volume 5" "Ellis, Eward S."
  , Book "The History of Our Country: Volume 6" "Ellis, Eward S."
  , Book "The History of Our Country: Volume 7" "Ellis, Eward S."
  , Book "The History of Our Country: Volume 8" "Ellis, Eward S."
  , Book
      "Deadhouse Gates: Book Two of The Malazan Book of the Fallen"
      "Erikson, Steven"
  , Book "Medea and Other Plays" "Euripides; Morwood, James"
  , Book
      "Teaching Chinese as a Foreign Language: Theories and Applications"
      "Everson, Michael Erwin; Xiao, Yun"
  , Book "Mafia to Mormon: My Conversion Story" "Facione, Mario"
  , Book "Picturing Texts" "Faigley, Lester"
  , Book "The Runelords" "Farland, David"
  , Book "Wizardborn: Book Three of 'The Runelords'" "Farland, David"
  , Book "The Art of SQL" "Faroult, Stéphane and Peter Robson"
  , Book "Heir of Stone" "Farrell, S. L."
  , Book "Holder of Lightning" "Farrell, S. L."
  , Book "Mage of Clouds (The Cloudmages #2)" "Farrell, S. L."
  , Book "Prince of the Blood" "Feist, Raymond E."
  , Book "Mistress of the Empire" "Feist, Raymond E.; Wurts, Janny"
  , Book "Daughter of the Empire" "Feist, Raymond E. and Janny Wurts"
  , Book "Servant of the Empire" "Feist, Raymond E. and Janny Wurts"
  , Book "China Today, China Tomorrow" "Fewsmith, Joseph"
  , Book "The Blue Roan Child" "Findlay, Jamieson"
  , Book
      "Treasure Island: Junior Classics for Young Readers"
      "Fletcher-Blume, Nancy"
  , Book "Lord Hornblower" "Forester, C.S."
  , Book
      "How to Read Literature Like a Professor: a Lively and Entertaining Guide to Reading Between the Lines"
      "Foster, Thomas C."
  , Book "Latinoamérica: presente y pasado" "Fox, Arturo A."
  , Book
      "City Upon a Hill: The Legacy of America's Founding"
      "Fox, Frank; Pope, Clayne"
  , Book "Saints at War III: I'll be Home for Christmas" "Freeman, Robert C."
  , Book "Biological Science" "Freeman, Scott"
  , Book
      "International Political Economy: Perspectives on Global Power and Wealth"
      "Frieden, Jeffry A.; Lake, David A.; Broz, J. Lawrence"
  , Book "The Wilding" "Friedman, C. S."
  , Book "Inkdeath" "Funke, Cornelia Caroline"
  , Book "Inkheart" "Funke, Cornelia Caroline"
  , Book "Inkspell" "Funke, Cornelia Caroline; Bell, Anthea"
  , Book "Dhiammara" "Furey, Maggie"
  , Book "Echo of Eternity" "Furey, Maggie"
  , Book "Spirit of the Stone" "Furey, Maggie"
  , Book "Sword of Flame" "Furey, Maggie"
  , Book "The Heart of Myrial" "Furey, Maggie"
  , Book "Kusudama Origami" "Fuse, Tomoko"
  , Book "Quick and Easy Origami Boxes" "Fuse, Tomoko"
  , Book "Unit Origami: Multidimensional Transformations" "Fuse, Tomoko"
  , Book "Teaching Adolescent Writers" "Gallagher, Kelly"
  , Book "Keepers of the Sword" "Galli, Guy Morgan"
  , Book "Elmer and the Dragon" "Gannett, Ruth Stiles"
  , Book "My Father's Dragon" "Gannett, Ruth Stiles"
  , Book "The Dragons of Blueland" "Gannett, Ruth Stiles"
  , Book
      "Collins Spanish-English, English-Spanish Dictionary"
      "García, Teresa Alvarez"
  , Book
      "Our Family Christmas: Creating Meaningful and Memorable Christ-Centered Traditions"
      "Gardiner, Christie"
  , Book "Leprechauns" "Gardner, Craig Shaw"
  , Book "Personal Finance" "Garman, E. Thomas; Forgue, Raymond"
  , Book
      "Teaching English as a Foreign Or Second Language, Second Edition: A Teacher Self-Development and Methodology Guide"
      "Gebhard, Jerry G."
  , Book "The Dragon Hunters" "Genesse, Paul"
  , Book "A History of Chinese Civilization" "Gernet, Jacques"
  , Book "Diadem: Selected Poems" "Giorgio, Marosa Di"
  , Book "Witch Baby and Me After Dark" "Gliori, Debi"
  , Book
      "Understanding Chinese Characters by Their Ancestral Forms"
      "Go, Gam P."
  , Book "Lord of the Flies" "Golding, William"
  , Book "Harvest of Empire: A History of Latinos in America" "González, Juan"
  , Book "Blood of the Fold" "Goodkind, Terry"
  , Book "Chainfire" "Goodkind, Terry"
  , Book "Confessor" "Goodkind, Terry"
  , Book "Debt of Bones" "Goodkind, Terry"
  , Book "Faith of the Fallen" "Goodkind, Terry"
  , Book "Naked Empire" "Goodkind, Terry"
  , Book "Phantom" "Goodkind, Terry"
  , Book "Soul of the Fire: A Sword of Truth Novel" "Goodkind, Terry"
  , Book "Stone of Tears: A Sword of Truth Novel" "Goodkind, Terry"
  , Book
      "Temple of the Winds: Book Four of 'The Sword of Truths'"
      "Goodkind, Terry"
  , Book "The First Confessor" "Goodkind, Terry"
  , Book "The Pillars of Creation" "Goodkind, Terry"
  , Book "Wizard's First Rule" "Goodkind, Terry"
  , Book "Personal History" "Graham, Katharine"
  , Book
      "Pride and Prejudice and Zombies: The Classic Regency Romance--now with Ultraviolent Zombie Mayhem"
      "Grahame-Smith, Seth; Austen, Jane; Parada, Roberto"
  , Book "The Fault in Our Stars" "Green, John"
  , Book "The Norton Anthology of English Literature" "Greenblatt, Stephen"
  , Book
      "The Norton Anthology of English Literature"
      "Greenblatt, Stephen; Abrams, Meyer Howard"
  , Book
      "The Norton Anthology of English Literature, Major Authors Edition: The Romantic Period Through the Twentieth Century And After"
      "Greenblatt, Stephen; Abrams, Meyer Howard"
  , Book
      "The Norton Anthology of English Literature, volume e"
      "Greenblatt; Abrams, Meyer Howard"
  , Book "The Human Factor" "Greene, Graham"
  , Book "Halloween" "Greer, Ben"
  , Book
      "The Wealth of Nature: Economics as if Survival Mattered"
      "Greer, John Michael"
  , Book
      "State Power and World Markets: The International Political Economy"
      "Grieco, Joseph M.; Ikenberry, G. John"
  , Book "Japanese Picture Scrolls" "Grilli, Elise"
  , Book "The Brothers Grimm: 101 Fairy Tales" "Grimm, Jacob; Grimm, Wilhelm"
  , Book "Random House Thesaurus" "Group, Random House Publishing"
  , Book "The Wind's Twelve Quarters: Short Stories" "Guin, Ursula K. Le"
  , Book "Chinese Politics and Government" "Guo, Sujian"
  , Book "Literature: A Pocket Anthology" "Gwynn, R. S."
  , Book
      "Your pregnancy & birth"
      "Gynecologists, American College of Obstetricians and"
  , Book
      "Hiroshima Diary: The Journal of a Japanese Physician, August 6-September 30, 1945"
      "Hachiya, Michihiko; Wells, Warner"
  , Book "A Writer's Reference with Exercises" "Hacker, Diana; Sommers, Nancy"
  , Book "Just Ella" "Haddix, Margaret Peterson"
  , Book "An Unfortunate Fairy Tale" "Hahn, Chanda"
  , Book "The Coldest Winter: America and the Korean War" "Halberstam, David"
  , Book
      "The Haldeman Diaries: Inside the Nixon White House"
      "Haldeman, Harry R."
  , Book "Princess Academy" "Hale, Shannon"
  , Book "Statistics with Stata: Updated for Version 8" "Hamilton, Lawrence C."
  , Book "The Exchange Student Survival Kit" "Hansel, Bettina"
  , Book "The Gunniwolf" "Harper, Wilhelmina"
  , Book "The Second Chance" "Harris, Wyatt"
  , Book "A Traveller’s History of China" "Haw, Stephen G."
  , Book
      "Venezuela's Chavismo and Populism in Comparative Perspective"
      "Hawkins, Kirk A."
  , Book "The House of the Seven Gables" "Hawthorne, Nathaniel"
  , Book "The Scarlet Letter" "Hawthorne, Nathaniel"
  , Book "The Fantastic Stay-Home-From-School Day" "Hayashi, Nancy"
  , Book "Rhapsody: Child of Blood" "Haydon, Elizabeth"
  , Book "Gadiantons and the silver sword" "Heimerdinger, Chris"
  , Book "Tennis Shoes and the Feathered Serpent" "Heimerdinger, Chris"
  , Book "Tennis shoes and the feathered serpent: a novel" "Heimerdinger, Chris"
  , Book "The Golden Crown: A Novel" "Heimerdinger, Chris"
  , Book
      "The Lost Scrolls: Continuing the Adventure of Tennis Shoes and the Seven Churches"
      "Heimerdinger, Chris"
  , Book "The Sacred Quest" "Heimerdinger, Chris"
  , Book "Warriors of Cumorah: A Novel" "Heimerdinger, Chris"
  , Book "We the People: The Dust Bowl" "Heinrichs, Ann"
  , Book "Dune Messiah" "Herbert, Frank"
  , Book "Dune: Book One in the Dune Chronicles" "Herbert, Frank"
  , Book "The Perfect Pumpkin Hunt" "Herman, Gail"
  , Book "The Histories" "Herodotus"
  , Book "Tower of London" "Hibbert, Christopher"
  , Book "October Sky" "Hickam, Homer H., Jr."
  , Book
      "Classroom Instruction That Works with English Language Learners"
      "Hill, Jane D.; Miller, Kirsten B."
  , Book "The Restorer: A Novel" "Hinck, Sharon"
  , Book "The Restorer's Journey" "Hinck, Sharon"
  , Book "The Restorer's Son" "Hinck, Sharon"
  , Book "Stand a Little Taller" "Hinckley, Gordon Bitner"
  , Book "Riddley Walker, Expanded Edition" "Hoban, Russell"
  , Book "Ship of Destiny" "Hobb, Robin"
  , Book
      "Real Intimacy: A Couples' Guide to Healthy, Genuine Sexuality"
      "Hodson, Kristin B.; Harrison, Thomas G.; Worthington, Alisha B."
  , Book
      "Calculus for Business, Economics, and the Social and Life Sciences"
      "Hoffmann, Laurence D.; Bradley, Gerald L.; Rosen, Kenneth H."
  , Book "Witch & Curse (Wicked)" "Holder, Nancy and Debbie Viguié"
  , Book "An Introduction to Sociolinguistics" "Holmes, Janet"
  , Book "The Odyssey" "Homer"
  , Book "U.S. Foreign Policy: The Paradox of World Power" "Hook, Steven W."
  , Book
      "Herbert Hoover, the Uncommon Man"
      "Hoover Presidential Library Association, Hoover Presidential Library"
  , Book "The Kite Runner" "Hosseini, Khaled"
  , Book "A history of modern Chinese fiction" "Hsia, Chih-tsing"
  , Book "Battlefield Earth: A Saga of the Year 3000" "Hubbard, L. Ron"
  , Book "Notre Dame de Paris" "Hugo, Victor"
  , Book "Les misérables" "Hugo, Victor"
  , Book
      "International Economics (BYU edition)"
      "Husted, Steven L.; Melvin, Michael"
  , Book "Hispanics in the Mormon Zion, 1912-1999" "Iber, Jorge"
  , Book "The Dangerous Book for Boys" "Iggulden, Hal"
  , Book
      "Hiroshima and Nagasaki: the physical, medical, and social effects of the atomic bombings"
      "Iinkai, Hiroshima-shi Nagasaki-shi Genbaku Saigaishi Henshū"
  , Book "The Merriam-Webster Thesaurus" "Inc, Merriam-Webster"
  , Book "Disney's The Lion King" "Ingoglia, Gina"
  , Book "Tales of the Alhambra" "Irving, Washington"
  , Book "Jesus the Christ" "James E. Talmage"
  , Book "The Turn of the Screw: The Aspern Papers" "James, Henry"
  , Book
      "The Question and Answer Book: Amazing World of Animals"
      "Jefferies, Lawrence"
  , Book "History of Provo, Utah" "Jensen, Jens Marinus"
  , Book "JPS Hebrew-English Tanakh" "Jewish Publication Society"
  , Book "Wild Grass" "Johnson, Ian"
  , Book
      "Political Science Research Methods"
      "Johnson, Janet Buttolph; Reynolds, H. T."
  , Book "Calculus" "Johnson, Richard Edward; Kiokemeister, Fred Ludwig"
  , Book "Howl's Moving Castle" "Jones, Diana Wynne"
  , Book "World's Wackiest Riddle Book" "Jones, Evelyn"
  , Book "A Crown of Swords: Book Seven of 'The Wheel of Time'" "Jordan, Robert"
  , Book
      "Crossroads of Twilight: Book Ten of 'The Wheel of Time'"
      "Jordan, Robert"
  , Book "Knife of Dreams: Book Eleven of 'The Wheel of Time'" "Jordan, Robert"
  , Book "Lord of Chaos: Book Six of 'The Wheel of Time'" "Jordan, Robert"
  , Book "New Spring: The Novel" "Jordan, Robert"
  , Book "The dragon reborn" "Jordan, Robert"
  , Book
      "The Eye of the World: Book One of 'The Wheel of Time'"
      "Jordan, Robert"
  , Book
      "The Fires of Heaven: Book Five of 'The Wheel of Time'"
      "Jordan, Robert"
  , Book "The Great Hunt: Book Two of 'The Wheel of Time'" "Jordan, Robert"
  , Book
      "The Path of Daggers: Book Eight of 'The Wheel of Time'"
      "Jordan, Robert"
  , Book "The Shadow Rising: Book Four of 'The Wheel of Time'" "Jordan, Robert"
  , Book "Winter's Heart: Book Nine of 'The Wheel of Time'" "Jordan, Robert"
  , Book
      "The Gathering Storm: Book Twelve of the Wheel of Time"
      "Jordan, Robert; Sanderson, Brandon"
  , Book
      "Towers of Midnight: Book Thirteen of The Wheel of Time"
      "Jordan, Robert; Sanderson, Brandon"
  , Book
      "A Memory of Light: Book Fourteen of The Wheel of Time"
      "Jordan, Robert; Sanderson, Brandon"
  , Book
      "The One-Eyed Man: A Fugue, With Winds and Accompaniment"
      "Jr, L. E. Modesitt; (Jr.), L. E. Modesitt"
  , Book "The Phantom Tollbooth" "Juster, Norton"
  , Book
      "Taiwan’s Statesman: Lee Teng-hui and Democracy in Asia"
      "Kagan, Richard C."
  , Book "Exiled: Memoirs of a Camel" "Karr, Kathleen"
  , Book "Tigana" "Kay, Guy Gavriel"
  , Book "Economics and Public Policy: An Analytical Approach" "Kearl, James R."
  , Book "The story of my life" "Keller, Helen"
  , Book "Spanish Verbs" "Kendris, Christopher"
  , Book
      "In the President's Secret Service: Behind the Scenes with Agents in the Line of Fire and the Presidents They Protect"
      "Kessler, Ronald"
  , Book "Diary of a Wimpy Kid: Greg Heffley's Journal" "Kinney, Jeff"
  , Book "Diary of a Wimpy Kid: Rodrick rules. 2" "Kinney, Jeff"
  , Book "Dog Days: Diary of a Wimpy Kid" "Kinney, Jeff"
  , Book "The Ugly Truth (Diary of a Wimpy Kid book 5)" "Kinney, Jeff"
  , Book "Kim" "Kipling, Rudyard"
  , Book "Child of Vengeance" "Kirk, David"
  , Book
      "World Englishes Paperback with Audio CD: Implications for International Communication and English Language Teaching"
      "Kirkpatrick, Andy"
  , Book "Super simple origami" "Kneissler, Irmgard; Lasting, Inger"
  , Book
      "The Story of Doctor Dolittle: Junior Classics for Young Readers"
      "Knight, Kathryn"
  , Book "The Princess of Trelian" "Knudsen, Michelle"
  , Book "Mahi's Story" "Kordi, Gohar"
  , Book "I Don't Want to Go!" "Korman, Justine"
  , Book "The Historian" "Kostova, Elizabeth"
  , Book "Principles of Marketing" "Kotler, Philip; Armstrong, Gary M."
  , Book "Mini-Mysteries Featuring Garfield" "Kraft, Jim"
  , Book "Disney's Pocahontas" "Kreider, Karen"
  , Book "The Book of Laughter and Forgetting: A Novel" "Kundera, Milan"
  , Book
      "Latin American State Building in Comparative Perspective"
      "Kurtz, Marcus J"
  , Book "A Wrinkle in Time" "L'Engle, Madeleine"
  , Book "A Wrinkle in Time" "L'Engle, Madeleine"
  , Book "A Swiftly Tilting Planet" "L'Engle, Madeleine "
  , Book "An Acceptable Time" "L'Engle, Madeleine "
  , Book "A Course in Phonetics" "Ladefoged, Peter; Johnson, Keith"
  , Book "Disney The Princess and the Frog: Kiss The Frog" "Lagonegro, Melissa"
  , Book "TinkerBell and the Lost Treasure" "Lagonegro, Melissa"
  , Book "The Namesake" "Lahiri, Jhumpa"
  , Book "Anna and the King of Siam" "Landon, Margaret"
  , Book
      "The Armchair Economist (revised and updated May 2012): Economics & Everyday Life"
      "Landsburg, Steven E."
  , Book "The Girl who Played with Fire" "Larsson, Stieg"
  , Book "The Girl with the Dragon Tattoo" "Larsson, Stieg"
  , Book "Chinese Traditional Festivals" "Latsch, Marie-Luise"
  , Book
      "The Columbia Anthology of Modern Chinese Literature"
      "Lau, Joseph and Howard Goldblatt"
  , Book "The Left Hand of Darkness" "Le Guin, Ursula K"
  , Book "Castles" "Lee, Alan and David Day"
  , Book "China" "Leffman, David; Lewis, Simon; Atiyah, Jeremy"
  , Book "The Norton Anthology of Theory and Criticism" "Leitch, Vincent B."
  , Book "Cinder and Ella" "Lemon, Melissa"
  , Book
      "Education and Racism: A Primer on Issues and Dilemmas"
      "Leonardo, Zeus; Grubb, W. Norton"
  , Book "Gregg Shorthand Simplified for Colleges" "Leslie, Louis A."
  , Book "The Misadventures of Benjamin Bartholomew Piff" "Lethcoe, Jason"
  , Book
      "The Box: How the Shipping Container Made the World Smaller and the World Economy Bigger"
      "Levinson, Marc"
  , Book "The Complete Chronicles of Narnia" "Lewis, C. S."
  , Book "The Jerusalem Windows of Marc Chagall" "Leymarie, Jean"
  , Book
      "Mandarin Chinese: A Functional Reference Grammar"
      "Li, Charles N.; Thompson, Sandra A."
  , Book "Tracing the Roots of Chinese Characters: 500 Cases" "Li, Leyi"
  , Book "A Child's Garden of Misinformation" "Linkletter, Art"
  , Book "变化中的中国Reading into a New China" "Liu, Ruinian; Li, Duanduan"
  , Book "Frog and Toad Are Friends" "Lobel, Arnold"
  , Book "Gathering Blue" "Lowry, Lois"
  , Book "The Giver" "Lowry, Lois"
  , Book "Best of all" "Lucado, Max"
  , Book "The Janson Directive" "Ludlum, Robert"
  , Book "Essentials of Geology" "Lutgens, Frederick K.; Tarbuck, Edward J."
  , Book "Crown of Midnight" "Maas, Sarah Janet"
  , Book "Empire of Storms" "Maas, Sarah Janet"
  , Book "Heir of Fire" "Maas, Sarah Janet"
  , Book "Queen of Shadows" "Maas, Sarah Janet"
  , Book "Throne of Glass" "Maas, Sarah Janet"
  , Book "Pendragon: Black Water" "MacHale, D. J."
  , Book "Pendragon: Raven Rise" "MacHale, D. J."
  , Book "Pendragon: The Lost City of Faar" "MacHale, D. J."
  , Book "Pendragon: The Merchant of Death" "MacHale, D. J."
  , Book "Pendragon: The Never War" "MacHale, D. J."
  , Book "Pendragon: The Quillan Games" "MacHale, D. J."
  , Book "Pendragon: The Reality Bug" "MacHale, D. J."
  , Book "Pendragon: The Rivers of Zadaa" "MacHale, D. J."
  , Book "Sarah, Plain and Tall" "MacLachlan, Patricia"
  , Book "Wicked" "Maguire, Gregory"
  , Book "The Columbia History of Chinese Literature" "Mair, Victor"
  , Book "The Mirror Prince" "Malan, Violette"
  , Book
      "The Arms of Krupp: The Rise and Fall of the Industrial Dynasty That Armed Germany at War"
      "Manchester, William"
  , Book "The Glory and the Dream: volume 1" "Manchester, William"
  , Book "The Glory and the Dream: volume 2" "Manchester, William"
  , Book "The Golden Spiral" "Mangum, Lisa"
  , Book "5 lb. Book of GRE Practice Problems" "Manhattan Prep, -Manhattan"
  , Book "Macroeconomics" "Mankiw, N. Gregory"
  , Book
      "Pocket Oxford Chinese Dictionary: English-Chinese, Chinese-English"
      "Manser, Martin H.; Zhu, Yuan; Wang, Liangbi; Ren, Yongchang; Wu, Jingrong"
  , Book
      "Decoding the Heavens: A 2,000-year-old-computer--and the Century-long Search to Discover Its Secrets"
      "Marchant, Jo"
  , Book
      "The Question and Answer Book: Amazing World of Plants"
      "Marcus, Elizabeth"
  , Book
      "Cracking the GMAT Premium Edition with 6 Practice Tests 2015"
      "Martz, Geoff; Robinson, Adam"
  , Book "All by Myself" "Mayer, Mercer"
  , Book "Trick or Treat, Little Critter" "Mayer, Mercer"
  , Book "Golden Dream: A Fuzzy Odyssey" "Mayhar, Ardath"
  , Book "Crystal Singer" "McCaffrey, Anne"
  , Book "Dragondrums" "McCaffrey, Anne"
  , Book "Dragonquest" "McCaffrey, Anne"
  , Book "Dragonsdawn : [a novel]" "McCaffrey, Anne"
  , Book "Dragonsinger" "McCaffrey, Anne"
  , Book
      "Beauty: A Retelling of the Story of Beauty and the Beast"
      "McKinley, Robin"
  , Book "Rose Daughter" "McKinley, Robin"
  , Book "Spindle’s End" "McKinley, Robin"
  , Book "Sunshine" "McKinley, Robin"
  , Book "The Blue Sword" "McKinley, Robin"
  , Book "The Hero and the Crown" "McKinley, Robin"
  , Book "Reinventing the Bazaar: A Natural History of Markets" "McMillan, John"
  , Book
      "Reading & Writing Chinese Simplified Character Edition"
      "McNaughton, William"
  , Book "Reading and Writing Chinese" "McNaughton, William and Li Ying"
  , Book "Chʻang Yung Han Tzu" "McNaughton, William; Ying, Li"
  , Book "Ruby the Red Fairy" "Meadows, Daisy"
  , Book "Wildwood" "Meloy, Colin"
  , Book "Keeper of the Lost Cities" "Messenger, Shannon"
  , Book "Keeper of the Lost Cities: Everblaze" "Messenger, Shannon"
  , Book "Keeper of the Lost Cities: Exile" "Messenger, Shannon"
  , Book "Keeper of the Lost Cities: Lodestar" "Messenger, Shannon"
  , Book "Keeper of the Lost Cities: Neverseen" "Messenger, Shannon"
  , Book "Let the Sky Fall" "Messenger, Shannon"
  , Book "Let the Storm Break" "Messenger, Shannon"
  , Book "Let the Wind Rise" "Messenger, Shannon"
  , Book "Requiem for the Living : A Memoir" "Metcalf, Jeff"
  , Book "Scarlet: The Lunar Chronicles" "Meyer, Marissa"
  , Book "Breaking Dawn" "Meyer, Stephenie"
  , Book "Eclipse" "Meyer, Stephenie"
  , Book "New Moon" "Meyer, Stephenie"
  , Book "Twilight" "Meyer, Stephenie"
  , Book "Perdido Street Station" "Miéville, China"
  , Book "The New England Mind: The Seventeenth Century" "Miller, Perry"
  , Book "Myst, The: Book of Atrus" "Miller, Robyn; Miller, Rand"
  , Book
      "Draw Near Unto Me: Daily Reflections on the Doctrine and Covenants"
      "Millet, Robert L. and Lloyd D. Newell"
  , Book
      "Jesus, the Very Thought of Thee: Daily Reflections of the New Testament"
      "Millet, Robert L. and Lloyd D. Newell"
  , Book
      "When Ye Shall Receive These Things: Daily Reflections on the Book of Mormon"
      "Millet, Robert L. and Lloyd D. Newell"
  , Book "Paradise Lost: 1 & 2" "Milton, John"
  , Book "On the Dignity of Man" "Mirandola, Giovanni Pico della"
  , Book "Cloud Atlas" "Mitchell, David"
  , Book "Apparitions: Ghosts of Old Edo: Ghosts of Old Edo" "Miyabe, Miyuki"
  , Book "Colors of Chaos" "Modesitt, L. E."
  , Book "Fall of Angels" "Modesitt, L. E."
  , Book "Ordermaster" "Modesitt, L. E."
  , Book "The Death of Chaos" "Modesitt, L. E."
  , Book "The Magic Engineer" "Modesitt, L. E."
  , Book "The white order" "Modesitt, L. E."
  , Book "Magi'i of Cyador" "Modesitt, L. E. Jr."
  , Book "The Chaos Balance" "Modesitt, L. E. Jr."
  , Book "The Magic of Recluce" "Modesitt, L. E. Jr."
  , Book "The Labyrinth of Dreaming Books" "Moers, Walter"
  , Book "Anne of Green Gables" "Montgomery, Lucy Maud"
  , Book "Utopia" "More, Thomas"
  , Book "The Secret Life of William Shakespeare" "Morgan, Jude"
  , Book "Uruguay: Enchantment of the World" "Morrison, Marion"
  , Book "Labyrinth" "Mosse, Kate"
  , Book "Me Before You" "Moyes, Jojo"
  , Book "The Qur’an" "Muhammad"
  , Book "Beyonders: A World Without Heroes" "Mull, Brandon"
  , Book "Fablehaven" "Mull, Brandon"
  , Book "Fablehaven: Rise of the Evening Star" "Mull, Brandon"
  , Book
      "National Politics in a Global Economy: The Domestic Sources of U. S. Trade Policy"
      "Mundo, Philip A."
  , Book
      "What Did the Internment of Japanese Americans Mean?"
      "Murray, Alice Yang"
  , Book
      "This Burning Land: Lessons from the Front Lines of the Transformed Israeli-Palestinian Conflict"
      "Myre, Greg; Griffin, Jennifer"
  , Book "Lectures on Faith" "N.B. Lundwall"
  , Book "Shiloh Season" "N.B. Lundwall"
  , Book "Origami Classroom" "Nakano, Dokuotei"
  , Book "The Guide" "Narayan, R. K."
  , Book "Saving Shiloh" "Naylor, Phyllis Reynolds"
  , Book "Shiloh" "Naylor, Phyllis Reynolds"
  , Book
      "Medical Nutrition Therapy: A Case Study Approach"
      "Nelms, Marcia; Roth, Sara Long; Lacey, Karen"
  , Book "Hope in our Hearts" "Nelson, Russell M."
  , Book "Five Children and It" "Nesbit, E."
  , Book "The Book of Dragons" "Nesbit, E."
  , Book "The Enchanted Castle" "Nesbit, E.; Millar, H."
  , Book "The Content Analysis Guidebook" "Neuendorf, Kimberly A."
  , Book
      "Report to JFK: The Skybolt Crisis in Perspective"
      "Neustadt, Richard E."
  , Book
      "Three Centuries of American Poetry and Prose"
      "Newcomer, Alphonso Gerald; Andrews, Alice Ebba; Hall, Howard Judson"
  , Book "The Covenant Rising: Book One of The Dreamtime" "Nicholls, Stan"
  , Book
      "Microeconomic Theory: Basic Principles and Extensions"
      "Nicholson, Walter"
  , Book
      "Microeconomic theory: basic principles and extensions"
      "Nicholson, Walter; Snyder, Christopher M."
  , Book
      "Affirming Diversity: The Sociopolitical Context of Multicultural Education"
      "Nieto, Sonia; Bode, Patty"
  , Book
      "Literature for Today's Young Adults"
      "Nilsen, Alleen Pace; Donelson, Kenneth L."
  , Book "Abhorsen" "Nix, Garth"
  , Book "Grim Tuesday (The Keys to the Kingdom, Book 2)" "Nix, Garth"
  , Book "Lirael: Daughter of the Clayr" "Nix, Garth"
  , Book "Sabriel" "Nix, Garth"
  , Book "Shade's Children" "Nix, Garth"
  , Book "Evermore: The Immortals" "Noël, Alyson"
  , Book "Shadowland: The Immortals" "Noël, Alyson"
  , Book "Blue Moon: The Immortals" "Noel, Alyson; Noël, Alyson"
  , Book "Benedict Arnold: Traitor to His Country" "Nolan, Jeannette Covert"
  , Book "Beacons: Stories for Our Not So Distant Future" "Norminton, Gregory"
  , Book
      "Ciara's Song: A Chronicle of Witch World"
      "Norton, Andre; McConchie, Lyn"
  , Book "The Duke's Ballad" "Norton, Andre; McConchie, Lyn"
  , Book "Imperial Lady: A Fantasy of Han China" "Norton, Andre; Shwartz, Susan"
  , Book "Throne of Jade" "Novik, Naomi"
  , Book "The Secret of the King" "Nunes, Rachel Ann; Ward, Jay Bryant"
  , Book
      "Understanding Arabs: A Guide for Modern Times"
      "Nydell, Margaret Kleffner"
  , Book
      "The Dragonlover's Guide to Pern"
      "Nye, Jody Lynn; McCaffrey, Anne; Hamilton, Todd Cameron; Clouse, James"
  , Book
      "Understanding Global Conflict and Cooperation: An Introduction to Theory and History"
      "Nye, Joseph S.; Welch, David"
  , Book "The Silver Crown" "O'Brien, Robert C."
  , Book
      "The Story of Peter Pan: Retold From the Fairy Play by Sir James Barrie"
      "O'Connor, Daniel Stephen"
  , Book "Pegasus: The New Olympians" "O’Hearn, Kate"
  , Book "Deathnote" "Ohba, Tsugumi"
  , Book "The Famished Road" "Okri, Ben"
  , Book "The Scarlet Pimpernel" "Orczy, Emmuska"
  , Book "Summer of the Sea Serpent" "Osborne, Mary Pope"
  , Book
      "Education Transformation: How K-12 Online Learning is bringing the greatest change to education in 100 years"
      "Packard, Ron"
  , Book "Common Sense" "Paine, Thomas"
  , Book "Política y poder en el gobierno de Menem" "Palermo, Vicente"
  , Book "Out of Mao’s Shadow" "Pan, Philip P."
  , Book "Everblue" "Pandos, Brenda"
  , Book "Brisingr" "Paolini, Christopher"
  , Book "Eldest" "Paolini, Christopher"
  , Book "Eragon" "Paolini, Christopher"
  , Book "Amelia Bedelia" "Parish, Peggy"
  , Book "Amelia Bedelia" "Parish, Peggy"
  , Book "Come Back, Amelia Bedelia" "Parish, Peggy"
  , Book "Bridge to Terabithia" "Paterson, Katherine"
  , Book "The Dark Hills Divide" "Patrick, Carman"
  , Book
      "The Penkovskiy Papers. Introd. and Commentary by Frank Gibney. Foreword by Edward Crankshaw. Translated by Peter Deriabin"
      "Penkovskiy, Oleg"
  , Book "Jane Goodall: The Woman who Redefined Man" "Peterson, Dale"
  , Book "Don't Break the Bank" "Peterson's Publishing"
  , Book "The History of Spain" "Pierson, Peter"
  , Book
      "God Wants You to Be Rich: How and Why Everyone Can Enjoy Material and Spiritual Wealth in Our Abundant World"
      "Pilzer, Paul Zane"
  , Book "Uncle Boris in the Yukon" "Pinkwater, Daniel"
  , Book
      "The Worst-Case Scenario Survival Handbook: Travel"
      "Piven, Joshua; Borgenicht, David"
  , Book
      "The Worst-Case Scenario Survival Handbook: Extreme Edition"
      "Piven, Joshua; Borgenicht, David; Worrick, Jennifer"
  , Book
      "Discussions of Modeling: Purpose and Practices in Economic Theory"
      "Platt, Brennan C."
  , Book "Tales of Mystery and Imagination" "Poe, Edgar Allan"
  , Book
      "Zero Prep: Ready-to-go Activities for the Language Classroom"
      "Pollard, Laurel; Hess, Natalie"
  , Book "The Prophecy" "Poole, Jeffrey"
  , Book
      "Visión de los vencidos: relaciones indígenas de la conquista"
      "Portilla, Miguel León"
  , Book "Me and Mr. Darcy: A Novel" "Potter, Alexandra"
  , Book "Bhagavad-gītā as it is" "Prabhupāda, A. C. Bhaktivedanta Swami"
  , Book "Film: A Critical Introduction" "Pramaggiore, Maria; Wallis, Tom"
  , Book "Malka" "Pressler, Mirjam"
  , Book "Collins Chinese Dictionary (Collins Gem)" "Publishers, HarperCollins"
  , Book "The Amber Spyglass" "Pullman, Philip"
  , Book "The Golden Compass" "Pullman, Philip"
  , Book "The Subtle Knife" "Pullman, Philip"
  , Book "A Train to Potevka" "Ramsdell, Mike"
  , Book "The Real Mother Goose" "Rand McNally"
  , Book "Atlas Shrugged" "Rand, Ayn"
  , Book
      "Little Women"
      "Randall, Ronne; Alcott, Louisa May; illustrator), Robert Dunn (Children's book"
  , Book
      "Random House Webster's Unabridged Dictionary"
      "Random House Publishing Group"
  , Book
      "Games and Information: An Introduction to Game Theory"
      "Rasmusen, Eric"
  , Book
      "Call of the Herald: Free Young Adult Epic Fantasy Book"
      "Rathbone, Brian"
  , Book "Dragon Prince" "Rawn, Melanie"
  , Book "Skybowl" "Rawn, Melanie"
  , Book "Stronghold" "Rawn, Melanie"
  , Book "Sunrunner's Fire" "Rawn, Melanie"
  , Book "The Dragon Token" "Rawn, Melanie"
  , Book "The Mageborn Traitor: Exiles vol. ii" "Rawn, Melanie"
  , Book "The Ruins of Ambrai: Exiles vol. i" "Rawn, Melanie"
  , Book "The Star Scroll" "Rawn, Melanie"
  , Book "The Reagan Diaries" "Reagan, Ronald"
  , Book "Please Don't Feed the Tiger Lily!" "Redbank, Tennant"
  , Book "The Great Fairy Race" "Redbank, Tennant"
  , Book "The Utah Redds and Their Progenitors" "Redd, Lura"
  , Book
      "The Soul of China: An interpretation of Chinese history"
      "Riencourt, Amaury de"
  , Book "Gulliver's Travels" "Riordan, James"
  , Book
      "Battle of the Labyrinth, The (Percy Jackson and the Olympians, Book 4)"
      "Riordan, Rick"
  , Book "Heroes of Olympus: The Son of Neptune" "Riordan, Rick"
  , Book
      "Last Olympian, The (Percy Jackson and the Olympians, Book 5)"
      "Riordan, Rick"
  , Book
      "Lightning Thief, The (Percy Jackson and the Olympians, Book 1)"
      "Riordan, Rick"
  , Book
      "Sea of Monsters, The (Percy Jackson and the Olympians, Book 2)"
      "Riordan, Rick"
  , Book "The Lost Hero" "Riordan, Rick"
  , Book "The Lost Hero (Heroes of Olympus)" "Riordan, Rick"
  , Book
      "The Mark of Athena (The Heroes of Olympus, Book Three)"
      "Riordan, Rick"
  , Book "The Red Pyramid" "Riordan, Rick"
  , Book
      "Titan’s Curse, The (Percy Jackson and the Olympians, Book 3)"
      "Riordan, Rick"
  , Book "Lady of the Forest" "Roberson, Jennifer"
  , Book "Sword-born: A Novel of Tiger and Del" "Roberson, Jennifer"
  , Book "Sword-breaker" "Roberson, Jennifer"
  , Book "Sword-Dancer" "Roberson, Jennifer"
  , Book "Sword-maker" "Roberson, Jennifer"
  , Book "Sword-Singer" "Roberson, Jennifer"
  , Book "Henry Reed, Inc" "Robertson, Keith"
  , Book "Housekeeping: A Novel" "Robinson, Marilynne"
  , Book
      "The Jungle Book: Junior Classics for Young Readers"
      "Robinson, W.T. and Kathryn Knight"
  , Book "Deltora Quest: Dread Mountain" "Rodda, Emily"
  , Book "ABC Dictionary of Chinese Proverbs" "Rohsenow, John Snowden"
  , Book
      "Blending Genre, Altering Style: Writing Multigenre Papers"
      "Romano, Tom"
  , Book
      "Modern Mandarin Chinese Grammar: A Practical Guide"
      "Ross, Claudia; Ma, Jing-heng Sheng"
  , Book "Joan of Arc" "Ross, Nancy Wilson"
  , Book "Goodbye, Columbus: And Five Short Stories" "Roth, Philip"
  , Book "Divergent" "Roth, Veronica"
  , Book "Insurgent" "Roth, Veronica"
  , Book "Harry Potter and the Chamber of Secrets" "Rowling, J. K."
  , Book "Harry Potter and the Goblet of Fire" "Rowling, J. K."
  , Book "Harry Potter and the Half-blood Prince" "Rowling, J. K."
  , Book "Harry Potter and the Order of the Phoenix" "Rowling, J. K."
  , Book "Harry Potter and the Prisoner of Azkaban" "Rowling, J. K."
  , Book "Harry Potter and the Sorcerer's Stone" "Rowling, J. K."
  , Book "The Tales of Beedle the Bard" "Rowling, J. K."
  , Book
      "Harry Potter and the Cursed Child"
      "Rowling, J. K., John Tiffany and Jack Thorne"
  , Book "Harry Potter and the Deathly Hallows (Book 7)" "Rowling, J.K."
  , Book
      "Harry Potter and the Sorcerer’s Stone (illustrated)"
      "Rowling, J.K. and Jim Kay"
  , Book
      "Harry Potter and the Chamger of Secrets (illustrated)"
      "Rowling, J.K. and Jim Kay"
  , Book
      "Harry Potter and the Prisoner of Azkaban (illustrated)"
      "Rowling, J.K. and Jim Kay"
  , Book "Pedro Páramo" "Rulfo, Juan; Peden, Margaret Sayers"
  , Book "Teddy Roosevelt, Rough Rider" "Sabin, Louis"
  , Book "Holes" "Sachar, Louis"
  , Book "Small steps" "Sachar, Louis"
  , Book
      "The Spread of Nuclear Weapons: An Enduring Debate"
      "Sagan, Scott Douglas; Waltz, Kenneth Neal"
  , Book "Siege of Darkness" "Salvatore, R. A."
  , Book "Starless Night" "Salvatore, R. A."
  , Book "The Legacy" "Salvatore, R. A."
  , Book "The Lone Drow" "Salvatore, R. A."
  , Book "The Thousand Orcs" "Salvatore, R. A."
  , Book "Iron and Silk" "Salzman, Mark"
  , Book "Elantris" "Sanderson, Brandon"
  , Book "Legion and The Emperor's Soul" "Sanderson, Brandon"
  , Book "Mistborn: The Final Empire" "Sanderson, Brandon"
  , Book "The Hero of Ages: Book Three of Mistborn" "Sanderson, Brandon"
  , Book "The Way of Kings" "Sanderson, Brandon"
  , Book "The Well of Ascension: Book Two of Mistborn" "Sanderson, Brandon"
  , Book "Warbreaker" "Sanderson, Brandon"
  , Book "Words of Radiance" "Sanderson, Brandon"
  , Book
      "Barefoot Running: How to Run Light and Free by Getting in Touch with the Earth"
      "Sandler, Michael; Lee, Jessica"
  , Book "Adolescence" "Santrock, John"
  , Book "Labtronics: Electronics for laboratory scientists" "Schmidt, L.M."
  , Book "The Riddle-a-day Riddle Book" "Schuller, Mary Ann"
  , Book
      "101 School Jokes: Guaranteed to Keep You Awake in Class"
      "Schultz, Sam"
  , Book "U.S. Diplomacy Since 1900" "Schulzinger, Robert D."
  , Book "Chinese Business Etiquette" "Seligman, Scott D."
  , Book "The Invention of Hugo Cabret" "Selznick, Brian"
  , Book
      "Is Everyone Really Equal?: An Introduction to Key Concepts in Social Justice Education"
      "Sensoy, Özlem; DiAngelo, Robin"
  , Book "Black Beauty" "Sewell, Anna"
  , Book "The Killer Angels: A Novel" "Shaara, Michael"
  , Book
      "The Guernsey Literary and Potato Peel Pie Society"
      "Shaffer, Mary Ann and Annie Barrows"
  , Book "Macbeth" "Shakespeare, William"
  , Book
      "Complete Pelican Shakespeare"
      "Shakespeare, William; Orgel, Stephen; Braunmuller, A. R."
  , Book "A Dictionary Of Maqiao" "Shaogong, Han; gong, han shao"
  , Book "Could I Keep Him?" "Shapiro, Arnold"
  , Book "Jonathan and the Dragon" "Shapiro, Irwin"
  , Book "Rickshaw Boy" "She, Lao"
  , Book
      "Frankenstein: The 1818 Text, Contexts, Criticism"
      "Shelley, Mary Wollstonecraft"
  , Book "The Fun Loving Gang: In Wrong Right" "Sherman, Herman Morrow"
  , Book "Outlaws of the Marsh" "Shi, Nai'an; Luo, Guanzhong"
  , Book "Dark Moon Defender" "Shinn, Sharon"
  , Book "Fortune and Fate" "Shinn, Sharon"
  , Book "Jenna Starborn" "Shinn, Sharon"
  , Book "Mystic and Rider" "Shinn, Sharon"
  , Book "Reader and Raelynx" "Shinn, Sharon"
  , Book "The Thirteenth House" "Shinn, Sharon"
  , Book
      "Power & Choice: An Introduction to Political Science"
      "Shively, W. Phillips"
  , Book "The Joy of Origami" "Sicklen, Margaret Van"
  , Book "Illustrated Stories from Around the World" "Sims, Lesley"
  , Book "Leven Thumps and the Gateway to Foo" "Skye, Obert"
  , Book "The No. 1 Ladies' Detective Agency" "Smith, Alexander McCall"
  , Book
      "History of the Church of Jesus Christ of Latter-day Saints: volume 1"
      "Smith, Joseph"
  , Book
      "History of the Church of Jesus Christ of Latter-Day Saints: volume 2"
      "Smith, Joseph"
  , Book
      "History of the Church of Jesus Christ of Latter-Day Saints: volume 3"
      "Smith, Joseph"
  , Book
      "History of the Church of Jesus Christ of Latter-Day Saints: volume 4"
      "Smith, Joseph"
  , Book
      "History of the Church of Jesus Christ of Latter-Day Saints: volume 5"
      "Smith, Joseph"
  , Book
      "History of the Church of Jesus Christ of Latter-Day Saints: volume 6"
      "Smith, Joseph"
  , Book
      "History of the Church of Jesus Christ of Latter-Day Saints: volume 7"
      "Smith, Joseph"
  , Book
      "Night World No. 1: Secret Vampire; Daughters of Darkness; Spellbinder"
      "Smith, L. J."
  , Book
      "Democracy in Latin America: Political Change in Comparative Perspective"
      "Smith, Peter Hopkinson"
  , Book "Inda" "Smith, Sherwood"
  , Book "King's Shield" "Smith, Sherwood"
  , Book "The Fox" "Smith, Sherwood"
  , Book "Treason's Shore" "Smith, Sherwood"
  , Book
      "Cultures at War: Moral Conflicts in Western Democracies"
      "Smith, T. Alexander; Tatalovich, Raymond"
  , Book "A Series of Unfortunate Events #2: The Reptile Room" "Snicket, Lemony"
  , Book "A Series of Unfortunate Events: The Austere Academy" "Snicket, Lemony"
  , Book "A Series of Unfortunate Events: The Ersatz Elevator" "Snicket, Lemony"
  , Book
      "A Series of Unfortunate Events: The Hostile Hospital"
      "Snicket, Lemony"
  , Book "A Series of Unfortunate Events: The Vile Village" "Snicket, Lemony"
  , Book "The hostile hospital 8" "Snicket, Lemony"
  , Book
      "A Series of Unfortunate Events: The End"
      "Snicket, Lemony; Helquist, Brett"
  , Book
      "A Series of Unfortunate Events: The Grim Grotto"
      "Snicket, Lemony; Helquist, Brett"
  , Book
      "A Practical Guide to Linux Commands, Editors, and Shell Programming"
      "Sobell, Mark G."
  , Book "Warning to the West" "Solzhenitsyn, Aleksandr"
  , Book "The Three Theban Plays" "Sophocles"
  , Book
      "Creating Writers: Through 6-trait Writing Assessment and Instruction"
      "Spandel, Vicki"
  , Book "Safe Haven" "Sparks, Nicholas"
  , Book "The Dark Side of Genius: The Life of Alfred Hitchcock" "Spoto, Donald"
  , Book
      "The Adventures of Huckleberry Finn: Junior Classics for Young Readers"
      "Stafford, Clay"
  , Book
      "The Wind in the Willows: Junior Classics for Young Readers"
      "Stafford, Clay"
  , Book "Tales for the Midnight Hour" "Stamper, Judith Bauer"
  , Book "The Millionaire Next Door" "Stanley, Thomas J.; Danko, William D."
  , Book "A Distant Thunder: Jayson Wolfe Series. bk. 2" "Stansfield, Anita"
  , Book "The sound of rain" "Stansfield, Anita"
  , Book "Towers of Brierley: A Novel" "Stansfield, Anita"
  , Book "Winds of Hope: A Novel" "Stansfield, Anita"
  , Book "Unicorns of Balinor: The Road to Balinor" "Stanton, Mary"
  , Book "The Emperor's Blades" "Staveley, Brian"
  , Book "Of Mice and Men" "Steinbeck, John"
  , Book "The Winter of Our Discontent" "Steinbeck, John"
  , Book "Linear Algebra for Dummies" "Sterling, Mary Jane"
  , Book "The Mystery of Dreams" "Stevens, William Oliver"
  , Book "The Mysterious Benedict Society" "Stewart, Trenton Lee"
  , Book "101 Silly Monster Jokes" "Stine, Robert Lawrence"
  , Book "Dracula" "Stoker, Bram"
  , Book "107 3/4 Elephant Jokes" "Stokes, Jack"
  , Book "Theft of Swords" "Sullivan, Michael"
  , Book "Confessions of Zeno" "Svevo, Italo"
  , Book "Moving Day" "Szekeres, Cyndy"
  , Book "The Bonesetter's Daughter" "Tan, Amy"
  , Book "The Hundred Secret Senses" "Tan, Amy"
  , Book "Penrod" "Tarkington, Booth"
  , Book "Penrod and Sam" "Tarkington, Booth"
  , Book "Penrod Jashber" "Tarkington, Booth"
  , Book "Seventeen" "Tarkington, Booth"
  , Book "The Little Friend" "Tartt, Donna"
  , Book "Roll of Thunder, Hear my Cry" "Taylor, Mildred"
  , Book "The Earth kingdom chronicles: The tale of Aang" "Teitelbaum, Michael"
  , Book "Origami Magic" "Temko, Florence"
  , Book "遠東漢字三千字典Far East 3000 Chineses Character Dictionary" "Teng, Shou-hsin"
  , Book "今日台灣:中級漢語課程Taiwan Today" "Teng, Shou-Hsin; Perry, Lo Sun"
  , Book
      "Minnesota’s Natural Heritage: An Ecological Perspective"
      "Tester, John R."
  , Book
      "The Daughter of Time, the collection of mystery classics"
      "Tey, Josephine"
  , Book
      "Daughters in My Kingdom"
      "The Church of Jesus Christ of Latter-Day Saints"
  , Book "Gospel Art Book" "The Church of Jesus Christ of Latter-day Saints"
  , Book "Gospel Principles" "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "History of the Church of Jesus Christ of Latter-Day Saints: Index"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "Hymns of The Church of Jesus Christ of Latter-day Saints"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "La ensenanza: El llamamiento mas importante"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "New Testament Seminary Student Guide"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "Our Heritage: A Brief History of The Church of Jesus Christ of Latter-day Saints"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book "Preach My Gospel" "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "Predicad mi evangelio"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "Teachings of Presidents of the Church: George Albert Smith"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "Teachings of Presidents of the Church: Joseph Fielding Smith"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "The Life and Teachings of Jesus and his Apostles"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "The Standard of Truth"
      "The Church of Jesus Christ of Latter-Day Saints"
  , Book
      "Triple combinacion: El libro de Mormon, Doctrina y convenios, y La perla de gran precio"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book
      "True to the Faith: A Gospel Reference"
      "The Church of Jesus Christ of Latter-day Saints"
  , Book "Origins: Book Three in the Missing Link Trilogy" "Thompson, Kate"
  , Book "History of the Peloponnesian War" "Thucydides"
  , Book "The Edge on the Sword" "Tingle, Rebecca"
  , Book "The Silmarillion" "Tolkien, J. R. John Ronald Reuel"
  , Book
      "The Return of the King: Being the Third Part of The Lord of the Rings"
      "Tolkien, J. R. R."
  , Book "Children of Húrin" "Tolkien, John Ronald Reuel"
  , Book
      "The Fellowship of the Ring: The Lord of the Rings--Part One"
      "Tolkien, John Ronald Reuel"
  , Book "The Hobbit, Or, There and Back Again" "Tolkien, John Ronald Reuel"
  , Book "The Hobbit, Or, There and Back Again" "Tolkien, John Ronald Reuel"
  , Book "The Two Towers" "Tolkien, John Ronald Reuel"
  , Book
      "Roverandom"
      "Tolkien, John Ronald Reuel; Scull, Christina; Hammond, Wayne G."
  , Book
      "The Legend of Sigurd and Gudrún"
      "Tolkien, John Ronald Reuel; Tolkien, Christopher"
  , Book "Behind the Secret Window" "Toll, Nelly"
  , Book "War and Peace: A Novel" "Tolstoy, Leo"
  , Book "The Coming of the King" "Tolstoy, Nikolai"
  , Book
      "Eats, Shoots & Leaves: The Zero Tolerance Approach to Punctuation"
      "Truss, Lynne"
  , Book
      "A Manual for Writers of Research Papers, Theses, and Dissertations: Chicago Style for Students and Researchers"
      "Turabian, Kate L.; Booth, Wayne C."
  , Book "Ninja" "Turnbull, Stephen"
  , Book
      "Origami Extravaganza! Folding Paper, a Book, and a Box: [Origami Kit with Book, 162 Papers, 45 Projects]"
      "Tuttle Publishing"
  , Book "Life on the Mississippi" "Twain, Mark"
  , Book
      "Grow Rich Slowly: The Merrill Lynch Guide to Retirement Planning"
      "Underwood, Don and Paul B. Brown"
  , Book "The Quest" "Ursenbach, O. F."
  , Book "The Design of Sites" "van Duyne, Landay and Hong"
  , Book
      "Las Misiones Antiguas: The Spanish Missions of Baja California"
      "Vernon, Edward Wood"
  , Book "The Aeneid of Virgil" "Virgil"
  , Book "Christmas on Miracle Lane" "Volk, Kaye Jacobs"
  , Book
      "Mathematical Statistics with Applications"
      "Wackerly, Dennis D.; Scheaffer, Richard L."
  , Book "Three Ways of Thought in Ancient China" "Waley, Arthur"
  , Book "Daughter of Light" "Walker, Pamela"
  , Book "The Mammoth Book of Steampunk" "Wallace, Sean"
  , Book "Disney Peter Pan" "Walt Disney Company"
  , Book "Disney Sticks and Stones" "Walt Disney Company"
  , Book "The Disney Fairies Story Collection" "Walt Disney Company"
  , Book
      "Chinese Mythology: An Encyclopedia of Myth and Legend"
      "Walters, Derek"
  , Book
      "Read Chinese: A Beginning Text in the Chinese Character"
      "Wang, Fang-yü"
  , Book
      "Chinese Odyssey: Innovative Chinese Courseware"
      "Wang, Xueying; Chi, Lichuang; Feng, Liping"
  , Book "That's not my hamster" "Watt, Fiona"
  , Book
      "Attack of the Deranged Mutant Killer Monster Snow Goons"
      "Watterson, Bill"
  , Book "Calvin and Hobbes: Sunday Pages 1985-1995" "Watterson, Bill"
  , Book
      "Homicidal Psycho Jungle Cat: A Calvin and Hobbes Collection"
      "Watterson, Bill"
  , Book "The Essential Calvin And Hobbes" "Watterson, Bill"
  , Book "The Revenge of the Baby-Sat" "Watterson, Bill"
  , Book "The History of Money" "Weatherford, Jack"
  , Book "One Hundred Allegorical Tales from Traditional China" "Wei, Jinzhi"
  , Book "Dragons of Spring Dawning" "Weis, Margaret; Hickman, Tracy"
  , Book "Test of the Twins" "Weis, Margaret; Hickman, Tracy"
  , Book "War of the Twins" "Weis, Margaret; Hickman, Tracy"
  , Book "War of the Twins" "Weis, Margaret; Hickman, Tracy"
  , Book "Time of the Twins" "Weis, Margaret; Hickman, Tracy; Williams, Michael"
  , Book
      "The Civil War Supply Catalogue: A Comprehensive Sourcebook of Products from the Civil War Era Available Today"
      "Wellikoff, Alan"
  , Book "Thinblade: Sovereign of the Seven Isles: Book One" "Wells, David"
  , Book "The Time Machine and The Invisible Man" "Wells, H.G."
  , Book "The Shadows (The Books of Elsewhere)" "West, Jacqueline"
  , Book "Extras" "Westerfeld, Scott"
  , Book "Pretties" "Westerfeld, Scott"
  , Book "Specials" "Westerfeld, Scott"
  , Book "My Little Book of Poems" "Western Publishing Inc"
  , Book
      "Walt Disney's Snow White and the Seven Dwarfs"
      "Western Publishing Inc"
  , Book "Walt Disney's The Rescuers" "Western Publishing Inc"
  , Book "The Book of Merlyn" "White, T. H."
  , Book
      "Latin American Politics and Development"
      "Wiarda, Howard J. and Harvey F. Kline"
  , Book
      "The Continuous Atonement: Christ Doesn't Just Make Up the Difference. He Makes All the Difference"
      "Wilcox, Brad"
  , Book "I'm My Mommy, I'm My Daddy" "Wilcox, Daniel"
  , Book
      "A Personal Testimony Concerning the Washington Temple"
      "Wilcox, Keith W."
  , Book "Diccionario Inglés-español, Español-inglés" "Williams, Edwin B."
  , Book "To Green Angel Tower Part 1" "Williams, Tad"
  , Book "To Green Angel Tower Part 2" "Williams, Tad"
  , Book "An Inch of Ashes" "Wingrove, David"
  , Book "The Girl on the Boat" "Wodehouse, P. G."
  , Book "Storm Thief" "Wooding, Chris"
  , Book "Introductory Econometrics: A Modern Approach" "Wooldridge, Jeffrey"
  , Book "Time to Read" "World Book Inc"
  , Book "The Caine Mutiny" "Wouk, Herman"
  , Book "Calling on Dragons" "Wrede, Patricia C."
  , Book "Dealing with Dragons" "Wrede, Patricia C."
  , Book "Searching for Dragons" "Wrede, Patricia C."
  , Book "Talking to Dragons" "Wrede, Patricia C."
  , Book "Christmas Jars" "Wright, Jason F."
  , Book "Native Son" "Wright, Richard"
  , Book "Directory of the 2014 Writers' Conferences & Centers" "writers"
  , Book "Hubbub" "writers"
  , Book
      "National Geographic: Sequoias: Scaling a Forest Giant - Pictures, More From National Geographic Magazine"
      "writers"
  , Book "Quarterly West" "writers"
  , Book "Western Humanities Review" "writers"
  , Book
      "Curse of the Mistwraith (The Wars of Light and Shadow, Book 1)"
      "Wurts, Janny"
  , Book "Fugitive Prince" "Wurts, Janny"
  , Book "Grand Conspiracy" "Wurts, Janny"
  , Book "Initiate's Trial" "Wurts, Janny"
  , Book "Keeper of the Keys" "Wurts, Janny"
  , Book "Master of White Storm" "Wurts, Janny"
  , Book "Peril’s Gate" "Wurts, Janny"
  , Book "Peril’s Gate" "Wurts, Janny"
  , Book "Shadowfane" "Wurts, Janny"
  , Book "Ships of Merior" "Wurts, Janny"
  , Book "Sorcerer’s Legacy" "Wurts, Janny"
  , Book "Stormed Fortress" "Wurts, Janny"
  , Book "Stormwarden" "Wurts, Janny"
  , Book "Traitor's Knot" "Wurts, Janny"
  , Book "That Way Lies Camelot" "Wurts, Janny"
  , Book "Warhost of Vastmark" "Wurts, Janny"
  , Book "The Monstrumologist" "Yancey, Rick"
  , Book
      "Forbidden Games and Video Poems: The Poetry of Yang Mu and Lo Ch'ing"
      "Yang, Mu; Ch'ing, Lo"
  , Book
      "Let's Play Games in Chinese"
      "Yao, Daozhong; Yao, Tao-Chung; McGinnis, Scott"
  , Book
      "The Essentials of Biblical Hebrew"
      "Yates, Kyle Monroe and John Joseph Owens"
  , Book "Falling Leaves" "Yen Mah, Adeline"
  , Book "Dragons of Silk" "Yep, Laurence"
  , Book "A Sending of Dragons" "Yolen, Jane"
  , Book "An Invitation To The Butterfly Ball" "Yolen, Jane"
  , Book "Dragon’s Blood" "Yolen, Jane"
  , Book "Sword of the Rightful King" "Yolen, Jane"
  , Book "White Jenna: Book Two of the Great Alta Saga" "Yolen, Jane"
  , Book "Kitchen" "Yoshimoto, Banana"
  , Book "The Monkey and the Monk" "Yu, Anthony"
  , Book "To Live: A Novel" "Yu, Hua"
  , Book "Developing Writing Skills in Chinese" "Yuan, Boping and Kan Qian"
  , Book "Misty Rain over the Li Jiang River" "Zhang, Li Ping"
  , Book "木蘭辭" "Zhang, Song Nan"
  , Book "Sword and Sorceress IX" "Zimmer Bradley, Marion"
  , Book "Sword and Sorceress XI" "Zimmer Bradley, Marion"
  , Book "Circle of Fire" "Zink, Michelle"
  , Book "Идиот: роман" "Достоевский, Федор Михайлович"
  , Book
      "The Gulag Archipelago, 1918-1956: an experiment in literary investigation"
      "Солженицын, Александр Исаевич"
  , Book "Modern Chinese Characters (现代汉字)" "尹斌庸; Rohsenow, John Snowden"
  , Book "繁華落盡見真淳Conduct of Life" "扎根教育持續會;鍾明君"
  , Book "汉字演变五百例:英文版.续编" "李乐毅"
  , Book "米丽的大秘密" "格里兹"
  , Book
      "通向中国: Innovative Chinese Courseware : Workbook vol 1"
      "王学英; Chi, Li-Chuang;冯力平"
  , Book
      "通向中国: Innovative Chinese Courseware: Textbook vol 2 and workbook vol 2"
      "王学英; Chi, Li-Chuang;冯力平"
  , Book "銀河玩具島" "郝廣才"
  , Book "蝴蝶新衣" "郝廣才; Battaglia, Maria"
  , Book "青蛙變變變" "郝廣才; Forestier, Isabelle"
  , Book "藍鬍子的故事" "郝廣才; Indre, Agnes;愛格妮絲"
  , Book "金魚王在哪裡" "郝廣才; Roth, Marianne"
  , Book "A Citizen's Guide to Utah State Government" ""
  , Book "A Multicultural Reader: Collection two" ""
  , Book
      "Diccionario de la Universidad de Chicago Inglés-Español Y Español-Inglés"
      ""
  , Book "Diccionario Español/inglés - Inglés/español - Test Record Four" ""
  , Book
      "English Grammar for Students of Spanish: The Study Guide for Those Learning Spanish"
      ""
  , Book "If I Stay" ""
  , Book "La biblia (porciones)" ""
  , Book "Nature's World of Wonders" ""
  , Book "The Last Apprentice: Revenge of the Witch" ""
  ]

getBookR :: Handler Value
getBookR = do
  $logInfo "logging >:)"
  $logWarn "logging >:)"
  $logError "logging >:)"
  returnJson dummyBooks
